spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://123.57.160.178:3306/br-video-dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: y3DCU5#g00&0E
  redis:
    host: r-2zeqk2ec6w61kg636epd.redis.rds.aliyuncs.com
    port: 6379
    password: tCn^n5EIYOjvD3R0

nginxIp:
nginxPushIp:
nginxRtmpPort:
nginxHlsPort:
nginxPrefix:
videoPath:
videoRequestPath:
videoFileSuffix:
connectZYGDIsEnable:
connectZYGD:
connectGJGWIsEnable:
connectGJGW:
server:
  port: 9000
logging:
  level:
    com.ruoyi: info
    org.springframework: info
    com.hikvision: info
ruoyi:
  profile: /home/ruoyi/uploadPath
gbs:
  host: 123.57.160.178:10000